---
- hosts: all
  tags: ["packages"]
  become: true
  tasks:
    - set_fact:
        pypkgfam: "python{{ ansible_python.version.major|replace('2','') }}"
    - name: Prevent APT from starting services when installing packages
      copy:
        dest: /usr/sbin/policy-rc.d
        content: |
          #!/bin/sh
          exit 101
        mode: 0755
    - apt:
        update_cache: yes
        cache_valid_time: 86400
    - package:
        state: present
        name:
          - postgresql-10
          - postgresql-contrib-10
          - postgresql-10-postgis-2.4
          - "{{ pypkgfam }}-psycopg2"
          - openjdk-8-jdk
          - tomcat8-user
