---
- hosts: all
  tags: ["database"]
  become: true
  tasks:
    - set_fact:
        dhisdbname: dhis2
        dhisdbuser: dhis
    - package:
        state: present
        name:
          - postgresql-10
          - postgresql-contrib-10
          - postgresql-10-postgis-2.4
          - python-psycopg2
          - python3-psycopg2
    - copy:
        dest: /etc/postgresql/10/main/conf.d/nossl.conf
        mode: 0644
        content: |
          # Avoid "out of shared memory" error for DHIS2
          max_locks_per_transaction = 1024
    - service:
        name: postgresql
        state: started
    - wait_for:
        state: started
        port: 5432
    - block:
        - postgresql_user:
            state: present
            name: "{{ dhisdbuser }}"
            role_attr_flags: NOCREATEDB,NOCREATEROLE,LOGIN,NOSUPERUSER
            encrypted: yes
        - postgresql_db:
            state: present
            name: "{{ dhisdbname }}"
            owner: "{{ dhisdbuser }}"
        - postgresql_ext:
            state: present
            db: "{{ dhisdbname }}"
            name: postgis
      become_user: postgres
