---
- hosts: all
  become: true
  tasks:
    - name: Prevent APT from starting services when installing packages
      copy:
        dest: /usr/sbin/policy-rc.d
        content: |
          #!/bin/sh
          exit 101
        mode: 0755
    - apt:
        update_cache: yes
        cache_valid_time: 86400
- import_playbook: common-cleanforami.yml
- import_playbook: common-packages.yml
- import_playbook: common-https.yml
- import_playbook: common-database.yml
