---
- hosts: all
  become: true
  vars:
    pypkgfam: "python{{ ansible_python.version.major|replace('2','') }}"
  tasks:
    - apt:
        update_cache: yes
        cache_valid_time: 86400
    - package:
        state: present
        name:
          - postgresql-10
          - postgresql-contrib-10
          - postgresql-10-postgis-2.4
          - "{{ pypkgfam }}-psycopg2"
          - openjdk-8-jdk
          - tomcat8-user
