---
- hosts: localhost
  become: yes
  vars:
    dhisdbname: dhis2
    dhisdbuser: dhis
    dhisdbpass: "{{ lookup('password', 'credentials/dhis.db.pass') }}"
    dhisdbencryptpass: "{{ lookup('password', 'credentials/dhis.db.encryptpass') }}"
  tasks:
    - service:
        name: postgresql
        state: started
    - wait_for:
        state: started
        port: 5432
    - postgresql_user:
        state: present
        name: "{{ dhisdbuser }}"
        password: "{{ dhisdbpass }}"
        encrypted: yes
      become_user: postgres
    - template:
        owner: root
        group: tomcat8
        mode: 0640
        dest: /etc/dhis/dhis.conf
        src: /etc/dhis/dhis.conf.j2
