---
- hosts: localhost
  vars:
    pypkgfam: "python{{ ansible_python.version.major|replace('2','') }}"
    dhisdbname: dhis2
    dhisdbuser: dhis
    dhisdbpass: "{{ lookup('password', 'credentials/dhis.db.pass') }}"
    dhisdbencryptpass: "{{ lookup('password', 'credentials/dhis.db.encryptpass') }}"
  tasks:
    - package:
        state: present
        name:
          - "{{ pypkgfam }}-psycopg2"
    - template:
        owner: root
        group: tomcat8
        mode: 0640
        dest: /etc/dhis/dhis.conf
        src: /etc/dhis/dhis.conf.j2
    - postgresql_user:
        state: present
        name: "{{ dhisdbuser }}"
        password: "{{ dhisdbpass }}"
      become_user: postgres
      become: yes
